---
- name: Ensuring SELinux is installed
  package:
    name: libselinux
    state: present
  tags:
    - "1.7.1"
    - "1.7.1.1"

# Section 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration, skipped.

- name: Ensuring SELinux mode is enforcing
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - "1.7.1"
    - "1.7.1.3"
    - "1.7.1.4"
    - "1.7.1.5"

# Section 1.7.1.6 Ensure no unconfined services exist, skipped.

- name: Ensuring SETroubleshoot is not installed
  package:
    name: setroubleshoot
    state: absent
  tags:
    - "1.7.1"
    - "1.7.1.7"

- name: Ensuring MCS Translation Service is not installed
  package:
    name: mcstrans
    state: absent
  tags:
    - "1.7.1"
    - "1.7.1.8"