---
################################################################################
# The Center for Internet Security (CIS) Benchmark for CentOS Linux 7 v3.0.0
# https://www.cisecurity.org/benchmark/centos_linux/
################################################################################

- name: 1. Initial Setup
  include_tasks: initial-setup/main.yml
  tags: "1"

- name: 2. Services
  include_tasks: services/main.yml
  tags: "2"

- name: 3. Network Configuration
  include_tasks: network-configuration/main.yml
  tags: "3"

- name: 4. Logging and Auditing
  include_tasks: logging-and-auditing/main.yml
  tags: "4"