---
################################################################################
# The Center for Internet Security (CIS) Benchmark for CentOS Linux 7 v3.0.0
# https://www.cisecurity.org/benchmark/centos_linux/
################################################################################

- name: 1. Initial Setup
  include_tasks: initial/main.yml
  tags: initial

- name: 2. Services
  include_tasks: services/main.yml
  tags: services

- name: 3. Network Configuration
  include_tasks: network/main.yml
  tags: network

- name: 4. Logging and Auditing
  include_tasks: logging/main.yml
  tags: logging