---
- name: Ensuring unecessary service clients are not installed
  package:
    name:
      - ypbind
      - rsh
      - talk
      - telnet
      - openldap-clients
    state: absent
  tags:
    - "2.3.1"
    - "2.3.2"
    - "2.3.3"
    - "2.3.4"
    - "2.3.5"