---
- name: Installing chrony
  package:
    name: chrony
    state: present
  tags:
    - "2.2.1"
    - "2.2.1.1"

- name: Configuring chronyd
  lineinfile:
    path: /etc/sysconfig/chronyd
    create: false
    regexp: OPTIONS=
    line: OPTIONS="-u chrony"
  tags:
    - "2.2.1"
    - "2.2.1.2"

- name: Restarting chronyd service
  service:
    name: chronyd
    state: restarted
    enabled: yes
  tags:
    - "2.2.1"

- name: Synchronizing date and time
  command: chronyc makestep
  tags:
    - "2.2.1"

# Section 2.2.1.3 Ensure ntp is configured, skipped.

- name: Ensuring unnecessary service servers are not installed
  package:
    name:
      - 'xorg-x11-server*'
      - avahi
      - avahi-autoipd
      - cups
      - dhcp
      - openldap-servers
      - nfs-utils
      - rpcbind
      - bind
      - vsftpd
      - httpd
      - dovecot
      - samba
      - squid
      - net-snmp
      - rsync
      - ypserv
      - telnet-server
    state: absent
  tags:
    - "2.2.2"
    - "2.2.3"
    - "2.2.4"
    - "2.2.5"
    - "2.2.6"
    - "2.2.7"
    - "2.2.8"
    - "2.2.9"
    - "2.2.10"
    - "2.2.11"
    - "2.2.12"
    - "2.2.13"
    - "2.2.14"
    - "2.2.15"
    - "2.2.17"
    - "2.2.18"
    - "2.2.19"

- name: Ensuring Postfix is configured for local-only mode
  lineinfile:
    path: /etc/postfix/main.cf
    create: false
    regexp: inet_interfaces =
    line: inet_interfaces = loopback-only
  tags:
    - "2.2.16"

- name: Restarting Postfix service
  service:
    name: postfix
    state: restarted
  tags:
    - "2.2.16"