---
- name: Ensuring SELinux is installed
  package:
    name: libselinux
    state: present
  tags:
    - "1.7.1"
    - "1.7.1.1"

- name: Ensuring bootup text is not desplayed
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'
  tags:
    - "1.7.1"
    - "1.7.1.2"

- name: Ensuring SELinux is not disabled in bootloader configuration
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX=""'
  tags:
    - "1.7.1"
    - "1.7.1.2"

- name: Updating GRUB2 configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  tags:
    - "1.7.1"
    - "1.7.1.2"

- name: Ensuring SELinux mode is enforcing
  selinux:
    policy: targeted
    state: enforcing
  tags:
    - "1.7.1"
    - "1.7.1.3"
    - "1.7.1.4"
    - "1.7.1.5"

# Section 1.7.1.6 Ensure no unconfined services exist, skipped.

- name: Ensuring SETroubleshoot is not installed
  package:
    name: setroubleshoot
    state: absent
  tags:
    - "1.7.1"
    - "1.7.1.7"

- name: Ensuring MCS Translation Service is not installed
  package:
    name: mcstrans
    state: absent
  tags:
    - "1.7.1"
    - "1.7.1.8"