---
- name: Removing /etc/motd file
  file:
    path: /etc/motd
    state: absent
  tags:
    - "1.8.1"
    - "1.8.1.1"

- name: Ensuring login warning banner is configured properly
  copy:
    content: 'Authorized uses only. All activity may be monitored and reported.'
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/issue
    - /etc/issue.net
  tags:
    - "1.8.1"
    - "1.8.1.2"
    - "1.8.1.3"
    - "1.8.1.5"
    - "1.8.1.6"