---
- name: Disabling IPv6
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  tags:
    - "3.1.1"

# Section 3.1.2 Ensure wireless interfaces are disabled, skipped.