---
- name: Ensuring permissions on /etc/ssh/sshd_config are configured
  file:
    path: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  tags:
    - "5.2.1"

- name: Getting the list of SSH private host key files
  find:
    paths: /etc/ssh
    recurse: yes
    file_type: file
    patterns: 'ssh_host_*_key'
  register: ssh_private_key
  tags:
    - "5.2.2"

- name: Ensuring permissions on SSH private host key files are configured
  file :
    path: "{{ item.path }}"
    state: file
    owner: root
    group: root
    mode: 0600
  with_items: "{{ ssh_private_key.files }}"
  tags:
    - "5.2.2"

- name: Getting the list of SSH public host key files
  find:
    paths: /etc/ssh
    recurse: yes
    file_type: file
    patterns: 'ssh_host_*_key.pub'
  register: ssh_public_key
  tags:
    - "5.2.3"

- name: Ensuring permissions on SSH public host key files are configured
  file :
    path: "{{ item.path }}"
    state: file
    owner: root
    group: root
    mode: 0644
  with_items: "{{ ssh_public_key.files }}"
  tags:
    - "5.2.3"

# Section 5.2.4 Ensure SSH access is limited, skipped.

- name: Ensuring SSH is configured properly
  lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^#LogLevel'
      line: LogLevel VERBOSE
    - regexp: '^X11Forwarding'
      line: X11Forwarding no
    - regexp: '^#MaxAuthTries'
      line: MaxAuthTries 4
    - regexp: '^#IgnoreRhosts'
      line: IgnoreRhosts yes
    - regexp: '^#HostbasedAuthentication'
      line: HostbasedAuthentication no
    - regexp: '^#PermitRootLogin'
      line: PermitRootLogin no
    - regexp: '^#PermitEmptyPasswords'
      line: PermitEmptyPasswords no
    - regexp: '^#PermitUserEnvironment'
      line: PermitUserEnvironment no
    - regexp: '^Ciphers'
      line: Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    - regexp: '^MACs'
      line: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
    - regexp: '^KexAlgorithms'
      line: KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
    - regexp: '^#ClientAliveInterval'
      line: ClientAliveInterval 300
    - regexp: '^#ClientAliveCountMax'
      line: ClientAliveCountMax 3
    - regexp: '^#LoginGraceTime'
      line: LoginGraceTime 60
    - regexp: '^#Banner'
      line: Banner /etc/issue.net
    - regexp: '^UsePAM'
      line: UsePAM yes
    - regexp: '^#AllowTcpForwarding'
      line: AllowTcpForwarding no
    - regexp: '^#MaxStartups'
      line: MaxStartups 10:30:60
    - regexp: '^#MaxSessions'
      line: MaxSessions 10
  tags:
    - "5.2.5"
    - "5.2.6"
    - "5.2.7"
    - "5.2.8"
    - "5.2.9"
    - "5.2.10"
    - "5.2.11"
    - "5.2.12"
    - "5.2.13"
    - "5.2.14"
    - "5.2.15"
    - "5.2.16"
    - "5.2.17"
    - "5.2.18"
    - "5.2.19"
    - "5.2.20"
    - "5.2.21"
    - "5.2.22"

- name: Reloading sshd configuration
  service:
    name: sshd
    state: reloaded
  tags:
    - "5.2.5"
    - "5.2.6"
    - "5.2.7"
    - "5.2.8"
    - "5.2.9"
    - "5.2.10"
    - "5.2.11"
    - "5.2.12"
    - "5.2.13"
    - "5.2.14"
    - "5.2.15"
    - "5.2.16"
    - "5.2.17"
    - "5.2.18"
    - "5.2.19"
    - "5.2.20"
    - "5.2.21"
    - "5.2.22"