---
- name: 5.1. Configure Time-Based Job Schedulers
  include_tasks: configure-time-based-job-schedulers.yml
  tags: "5.1"

- name: 5.2. Configure SSH Server
  include_tasks: configure-ssh-server.yml
  tags: "5.2"