---
- name: 5.1. Configure Time-Based Job Schedulers
  include_tasks: configure-time-based-job-schedulers.yml
  tags: "5.1"

- name: 5.2. Configure SSH Server
  include_tasks: configure-ssh-server.yml
  tags: "5.2"

- name: 5.3. Configure PAM
  include_tasks: configure-pam.yml
  tags: "5.3"

- name: 5.4. User Accounts and Environment
  include_tasks: user-accounts-and-environment.yml
  tags: "5.4"

# Section 5.5 Ensure root login is restricted to system console, skipped.

- name: 5.6. Ensure Access To The Su Command Is Restricted
  group:
    name: sugroup
    state: present
  tags: "5.6"

- name: 5.6. Ensure Access To The Su Command Is Restricted (Cont'd)
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^#auth(.*)required(.*)$'
    line: 'auth            required        pam_wheel.so use_uid group=sugroup'
  tags: "5.6"