---
- name: 5.1. Configure Time-Based Job Schedulers
  include_tasks: configure-time-based-job-schedulers.yml
  tags: "5.1"

- name: 5.2. Configure SSH Server
  include_tasks: configure-ssh-server.yml
  tags: "5.2"

- name: 5.3. Configure PAM
  include_tasks: configure-pam.yml
  tags: "5.3"

- name: 5.4. User Accounts and Environment
  include_tasks: user-accounts-and-environment.yml
  tags: "5.4"