---
- name: Configuring password expiration
  lineinfile:
    path: /etc/login.defs
    create: false
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^PASS_MAX_DAYS'
      line: 'PASS_MAX_DAYS   365'
    - regexp: '^PASS_MIN_DAYS'
      line: 'PASS_MIN_DAYS   1'
    - regexp: '^PASS_WARN_AGE'
      line: 'PASS_WARN_AGE   7'
  tags:
    - "5.4.1"
    - "5.4.1.1"
    - "5.4.1.2"
    - "5.4.1.3"

- name: Ensuring inactive password lock is 30 days or less
  command: useradd -D -f 30
  tags:
    - "5.4.1"
    - "5.4.1.4"

# Section 5.4.1.5 Ensure all users last password change date is in the past, skipped.
# Section 5.4.2 Ensure system accounts are secured, skipped.

- name: Ensuring the default group for the root account is GID 0
  command: usermod -g 0 root
  tags:
    - "5.4.3"

- name: Ensuring default user shell timeout is configured
  blockinfile:
    path: /etc/profile
    block: |
      TMOUT=900
      readonly TMOUT
      export TMOUT
  tags:
    - "5.4.4"

# Section 5.4.5 Ensure default user umask is configured, skipped.