---
# Section 6.1.1 Audit system file permissions, skipped.

- name: Ensuring system file permissions in the /etc directory
  become_user: root
  file:
    path: "{{ item.path }}"
    state: file
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - path: /etc/passwd
      mode: '644'
    - path: /etc/shadow
      mode: '000'
    - path: /etc/group
      mode: '644'
    - path: /etc/gshadow
      mode: '000'
    - path: /etc/passwd-
      mode: '644'
    - path: /etc/shadow-
      mode: '000'
    - path: /etc/group-
      mode: '644'
    - path: /etc/gshadow-
      mode: '000'
  tags:
    - "6.1.2"
    - "6.1.3"
    - "6.1.4"
    - "6.1.5"
    - "6.1.6"
    - "6.1.7"
    - "6.1.8"
    - "6.1.9"

# Section 6.1.10 Ensure no world writable files exist, skipped.
# Section 6.1.11 Ensure no unowned files or directories exist, skipped.
# Section 6.1.12 Ensure no ungrouped files or directories exist, skipped.
# Section 6.1.13 Audit SUID executables, skipped.
# Section 6.1.14 Audit SGID executables, skipped.